apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlsform-builder.frontendFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xlsform-builder.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app.kubernetes.io/name: {{ include "xlsform-builder.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: http
