apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlsform-builder.pyxformFullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xlsform-builder.name" . }}
    app.kubernetes.io/component: pyxform
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.pyxform.type }}
  selector:
    app.kubernetes.io/name: {{ include "xlsform-builder.name" . }}
    app.kubernetes.io/component: pyxform
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.pyxform.port }}
      targetPort: http
